<?php
if (!defined('ABSPATH')) { exit; }
$css=<<<'CSS'
.zo-game-root--silent-rhythm-shooter{max-width:900px;margin:0 auto;padding:18px;border-radius:24px;background:linear-gradient(180deg,#121015,#2a1d33);color:#f7effa;font-family:"Trebuchet MS","Segoe UI",sans-serif}.zo-game-root--silent-rhythm-shooter *{box-sizing:border-box}.srs-top{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:14px}.srs-stat,.srs-panel{background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.1);border-radius:16px;padding:12px}.srs-stat strong{display:block;font-size:12px;text-transform:uppercase;color:#cdb7d7}.srs-track{display:grid;grid-template-columns:repeat(12,1fr);gap:6px;background:#0d0a11;padding:12px;border-radius:18px}.srs-cell{aspect-ratio:1;border-radius:10px;background:#241b2b;display:flex;align-items:center;justify-content:center;font-size:20px}.srs-btns{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.srs-btn{border:0;border-radius:12px;padding:10px 14px;background:#ff7b72;color:#261920;font-weight:700;cursor:pointer}
CSS;
$js=<<<'JS'
document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.zo-game-root--silent-rhythm-shooter').forEach(function(root){const trackEl=root.querySelector('[data-track]'),beatEl=root.querySelector('[data-beat]'),comboEl=root.querySelector('[data-combo]'),enemyEl=root.querySelector('[data-enemy]'),patternEl=root.querySelector('[data-pattern]'),goalEl=root.querySelector('[data-goal]'),logEl=root.querySelector('[data-log]');let s;function reset(){s={beat:1,combo:0,enemies:[4,8,11],shots:[],pattern:[],kills:0,log:'There is no music track. Your shots create the rhythm, and enemies sync to your tempo.'};render()}function fire(){if(s.kills>=6)return;s.shots.push(s.beat);const gap=s.pattern.length? s.beat-s.pattern[s.pattern.length-1] : 0;s.pattern.push(s.beat);if(gap>0&&gap<=3)s.combo++;else if(s.pattern.length>1)s.combo=0;s.enemies=s.enemies.filter(function(pos){if(pos===1){s.kills++;s.log='Shot on beat. An enemy synced into your bullet.';return false}return true});advance()}function waitBeat(){advance()}function advance(){s.beat++;s.enemies=s.enemies.map(function(pos){return pos-1}).filter(function(pos){return pos>0});if(s.enemies.some(pos=>pos===1)&&s.pattern.length>0){const lastGap=s.pattern.length>1?s.pattern[s.pattern.length-1]-s.pattern[s.pattern.length-2]:2;if(lastGap===2){s.log='The enemy matched your rhythm and rushed early.';s.kills=Math.max(0,s.kills-1)}}while(s.enemies.length<3&&s.kills<6)s.enemies.push(12+Math.floor(Math.random()*2));render()}function render(){trackEl.innerHTML='';for(let i=1;i<=12;i++){const c=document.createElement('div');c.className='srs-cell';if(s.enemies.includes(i))c.textContent='◇';if(i===1)c.textContent='▲';if(s.enemies.includes(i)&&i===1)c.textContent='✦';trackEl.appendChild(c)}beatEl.textContent=String(s.beat);comboEl.textContent=String(s.combo);enemyEl.textContent=String(s.enemies.length);patternEl.textContent=s.pattern.slice(-4).join(', ')||'none';goalEl.textContent=s.kills+'/6';if(s.kills>=6)logEl.textContent='You authored the rhythm and the room moved to your gunfire.';else logEl.textContent=s.log}root.querySelector('[data-fire]').addEventListener('click',fire);root.querySelector('[data-wait]').addEventListener('click',waitBeat);root.querySelector('[data-restart]').addEventListener('click',reset);reset()})});
JS;
if(!function_exists('zo_game_silent_rhythm_shooter_render')){function zo_game_silent_rhythm_shooter_render($post_id=0,$module=array()){ob_start();?>
<div class="zo-game-root zo-game-root--silent-rhythm-shooter">
<h2>Silent Rhythm Shooter</h2><p>No music track. You create rhythm by firing, and enemies learn to sync to the beat pattern you make.</p>
<div class="srs-top"><div class="srs-stat"><strong>Beat</strong><span data-beat>1</span></div><div class="srs-stat"><strong>Combo</strong><span data-combo>0</span></div><div class="srs-stat"><strong>Enemies</strong><span data-enemy>3</span></div><div class="srs-stat"><strong>Pattern</strong><span data-pattern>none</span></div><div class="srs-stat"><strong>Goal</strong><span data-goal>0/6</span></div></div>
<div class="srs-track" data-track></div>
<div class="srs-panel"><div class="srs-btns"><button class="srs-btn" data-fire>Fire</button><button class="srs-btn" data-wait>Wait Beat</button><button class="srs-btn" data-restart>Restart</button></div><p data-log></p></div>
</div>
<?php return ob_get_clean();}}
return array('slug'=>'silent-rhythm-shooter','name'=>'Silent Rhythm Shooter','author'=>'Arslan','description'=>'A shooter where your firing creates the rhythm and enemies sync to it.','render_callback'=>'zo_game_silent_rhythm_shooter_render','inline_style'=>$css,'inline_script'=>$js);
