<?php
if (!defined('ABSPATH')) { exit; }
$css=<<<'CSS'
.zo-game-root--ink-detective{max-width:880px;margin:0 auto;padding:18px;border-radius:24px;background:linear-gradient(180deg,#eef2f5,#c9d5df);color:#1e2a35;font-family:Georgia,serif}.zo-game-root--ink-detective *{box-sizing:border-box}.id-top{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:14px}.id-stat,.id-panel{background:rgba(255,255,255,.6);border:1px solid rgba(30,42,53,.12);border-radius:16px;padding:12px}.id-stat strong{display:block;font-size:12px;text-transform:uppercase;color:#5a6c7a}.id-clues{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.id-card{min-height:140px;border-radius:18px;padding:14px;background:#f9fbfd;border:1px solid rgba(30,42,53,.08)}.id-btns{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.id-btn{border:0;border-radius:12px;padding:10px 14px;background:#355c7d;color:#fff;font-weight:700;cursor:pointer}
CSS;
$js=<<<'JS'
document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.zo-game-root--ink-detective').forEach(function(root){const filterEl=root.querySelector('[data-filter]'),foundEl=root.querySelector('[data-found]'),caseEl=root.querySelector('[data-case]'),goalEl=root.querySelector('[data-goal]'),cardsEl=root.querySelectorAll('[data-card]'),logEl=root.querySelector('[data-log]');const filters=['Daylight','UV','Red','Blue'];let s;function reset(){s={index:0,found:new Set(),caseNo:1,clues:[{name:'Ticket',show:'UV',text:'Train 9, seat 14.'},{name:'Ledger',show:'Red',text:'Payment moved at dusk.'},{name:'Letter',show:'Blue',text:'Meet near the old bridge.'}],log:'Switch filters. Different inks reveal different clues.'};render()}function setFilter(i){s.index=i;cardsEl.forEach(function(card,idx){const c=s.clues[idx];card.textContent=filters[i]===c.show?c.text:'Nothing useful yet.';if(filters[i]===c.show)s.found.add(c.name)});if(s.found.size===3)s.log='Case solved. The clues only made sense under the right light.';else s.log='You changed the filter and new ink surfaced.';render()}function nextCase(){if(s.found.size<3){s.log='You need all 3 clues before you can close the case.';render();return}s.caseNo++;s.clues=[{name:'Map',show:'Blue',text:'Warehouse B is circled.'},{name:'Photo',show:'UV',text:'A glove print glows on the frame.'},{name:'Receipt',show:'Red',text:'The item was paid in cash.'}];s.found=new Set();s.log='New case. The old tricks may not match the new inks.';setFilter(0)}function render(){filterEl.textContent=filters[s.index];foundEl.textContent=s.found.size+'/3';caseEl.textContent=String(s.caseNo);goalEl.textContent=s.found.size===3?'Close case':'Reveal all clues';logEl.textContent=s.log}root.querySelectorAll('[data-set-filter]').forEach(function(btn){btn.addEventListener('click',function(){setFilter(Number(btn.getAttribute('data-set-filter')))})});root.querySelector('[data-next-case]').addEventListener('click',nextCase);root.querySelector('[data-restart]').addEventListener('click',reset);reset();setFilter(0)})});
JS;
if(!function_exists('zo_game_ink_detective_render')){function zo_game_ink_detective_render($post_id=0,$module=array()){ob_start();?>
<div class="zo-game-root zo-game-root--ink-detective">
<h2>Ink Detective</h2><p>Clues appear only under specific light filters. Change the light and rebuild the truth.</p>
<div class="id-top"><div class="id-stat"><strong>Case</strong><span data-case>1</span></div><div class="id-stat"><strong>Filter</strong><span data-filter>Daylight</span></div><div class="id-stat"><strong>Clues Found</strong><span data-found>0/3</span></div><div class="id-stat"><strong>Goal</strong><span data-goal>Reveal all clues</span></div></div>
<div class="id-clues"><div class="id-card" data-card>Nothing useful yet.</div><div class="id-card" data-card>Nothing useful yet.</div><div class="id-card" data-card>Nothing useful yet.</div></div>
<div class="id-panel"><div class="id-btns"><button class="id-btn" data-set-filter="0">Daylight</button><button class="id-btn" data-set-filter="1">UV</button><button class="id-btn" data-set-filter="2">Red</button><button class="id-btn" data-set-filter="3">Blue</button><button class="id-btn" data-next-case>Next Case</button><button class="id-btn" data-restart>Restart</button></div><p data-log></p></div>
</div>
<?php return ob_get_clean();}}
return array('slug'=>'ink-detective','name'=>'Ink Detective','author'=>'Arslan','description'=>'Switch light filters to reveal hidden clues and solve cases.','render_callback'=>'zo_game_ink_detective_render','inline_style'=>$css,'inline_script'=>$js);
