<?php
if (!defined('ABSPATH')) { exit; }
$css=<<<'CSS'
.zo-game-root--microbe-rts{max-width:900px;margin:0 auto;padding:18px;border-radius:24px;background:linear-gradient(180deg,#f2fff8,#bde7d4);color:#173329;font-family:"Trebuchet MS","Segoe UI",sans-serif}.zo-game-root--microbe-rts *{box-sizing:border-box}.mr-top{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:14px}.mr-stat,.mr-panel{background:rgba(255,255,255,.62);border:1px solid rgba(23,51,41,.12);border-radius:16px;padding:12px}.mr-stat strong{display:block;font-size:12px;text-transform:uppercase;color:#527362}.mr-board{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;background:#77b99d;padding:12px;border-radius:18px}.mr-cell{aspect-ratio:1;border-radius:12px;background:#e8fff2;display:flex;align-items:center;justify-content:center;font-size:22px;cursor:pointer}.mr-btns{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.mr-btn{border:0;border-radius:12px;padding:10px 14px;background:#2f8c61;color:#fff;font-weight:700;cursor:pointer}
CSS;
$js=<<<'JS'
document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.zo-game-root--microbe-rts').forEach(function(root){const boardEl=root.querySelector('[data-board]'),massEl=root.querySelector('[data-mass]'),mutEl=root.querySelector('[data-mutation]'),immuneEl=root.querySelector('[data-immune]'),goalEl=root.querySelector('[data-goal]'),turnEl=root.querySelector('[data-turn]'),logEl=root.querySelector('[data-log]');let s;function key(x,y){return x+','+y}function reset(){s={owned:new Set(['0,2','0,3']),enemy:new Set(['5,1','5,4']),mass:2,mutation:0,turn:1,selected:null,log:'Expand across the body. Mutation helps you survive immune attacks.'};render()}function clickCell(x,y){const k=key(x,y);if(s.owned.has(k)){s.selected=k;s.log='Cell colony selected. Expand into a neighboring tile.'}else if(s.selected){const p=s.selected.split(',');if(Math.abs(Number(p[0])-x)+Math.abs(Number(p[1])-y)===1&&!s.enemy.has(k)){s.owned.add(k);s.mass++;s.log='Colony expanded. New tissue claimed.';immuneTurn();s.selected=null}}render()}function mutate(){if(s.mass<2)return;s.mass-=2;s.mutation++;s.log='Mutation purchased. Your cells resist the next immune sweep.';render()}function immuneTurn(){s.turn++;const targets=[...s.owned].filter(function(k){const p=k.split(',');return Number(p[0])>2});if(targets.length){const hit=targets[Math.floor(Math.random()*targets.length)];if(s.mutation>0){s.mutation--;s.log='Immune attack blocked by mutation.'}else{s.owned.delete(hit);s.mass=Math.max(1,s.mass-1);s.log='Immune cells destroyed one outer colony.'}}if(s.owned.size>=12)s.log='Body sector dominated. Your microbe swarm survived and spread.'}function render(){boardEl.innerHTML='';for(let y=0;y<6;y++){for(let x=0;x<6;x++){const k=key(x,y),c=document.createElement('button');c.type='button';c.className='mr-cell';if(s.enemy.has(k))c.textContent='🛡';if(s.owned.has(k))c.textContent=s.selected===k?'🧫':'🦠';c.addEventListener('click',function(){clickCell(x,y)});boardEl.appendChild(c)}}massEl.textContent=String(s.mass);mutEl.textContent=String(s.mutation);immuneEl.textContent=s.mutation>0?'Resistant':'Fragile';goalEl.textContent=s.owned.size+'/12';turnEl.textContent=String(s.turn);logEl.textContent=s.log}root.querySelector('[data-mutate]').addEventListener('click',mutate);root.querySelector('[data-restart]').addEventListener('click',reset);reset()})});
JS;
if(!function_exists('zo_game_microbe_rts_render')){function zo_game_microbe_rts_render($post_id=0,$module=array()){ob_start();?>
<div class="zo-game-root zo-game-root--microbe-rts">
<h2>Microbe RTS</h2><p>Control cells inside a body. Expand, mutate, and survive immune attacks long enough to take over tissue.</p>
<div class="mr-top"><div class="mr-stat"><strong>Mass</strong><span data-mass>2</span></div><div class="mr-stat"><strong>Mutation</strong><span data-mutation>0</span></div><div class="mr-stat"><strong>Immune Status</strong><span data-immune>Fragile</span></div><div class="mr-stat"><strong>Colonies</strong><span data-goal>2/12</span></div><div class="mr-stat"><strong>Turn</strong><span data-turn>1</span></div></div>
<div class="mr-board" data-board></div>
<div class="mr-panel"><div class="mr-btns"><button class="mr-btn" data-mutate>Mutate</button><button class="mr-btn" data-restart>Restart</button></div><p data-log></p></div>
</div>
<?php return ob_get_clean();}}
return array('slug'=>'microbe-rts','name'=>'Microbe RTS','author'=>'Arslan','description'=>'Expand a microbe colony, mutate, and survive immune attacks inside a body.','render_callback'=>'zo_game_microbe_rts_render','inline_style'=>$css,'inline_script'=>$js);
