<?php
if (!defined('ABSPATH')) { exit; }
$css=<<<'CSS'
.zo-game-root--language-builder{max-width:920px;margin:0 auto;padding:18px;border-radius:24px;background:linear-gradient(180deg,#f9f1ff,#ddc9ef);color:#2c1f37;font-family:Georgia,serif}.zo-game-root--language-builder *{box-sizing:border-box}.lb-top{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:14px}.lb-stat,.lb-panel{background:rgba(255,255,255,.6);border:1px solid rgba(44,31,55,.12);border-radius:16px;padding:12px}.lb-stat strong{display:block;font-size:12px;text-transform:uppercase;color:#7a6588}.lb-words{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.lb-word{padding:14px;border-radius:16px;background:#fff9ff;border:1px solid rgba(44,31,55,.08)}.lb-btns{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.lb-btn{border:0;border-radius:12px;padding:10px 14px;background:#7f56a3;color:#fff;font-weight:700;cursor:pointer}
CSS;
$js=<<<'JS'
document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.zo-game-root--language-builder').forEach(function(root){const wordEls=root.querySelectorAll('[data-word]'),powerEl=root.querySelector('[data-power]'),goalEl=root.querySelector('[data-goal]'),stepEl=root.querySelector('[data-step]'),spellEl=root.querySelector('[data-spell]'),logEl=root.querySelector('[data-log]');const syllables=[{part:'ka',power:'move'},{part:'ru',power:'open'},{part:'mi',power:'light'}];let s;function reset(){s={step:1,power:0,spell:[],goal:['move'],log:'Invent a language. Combine syllables and test whether your word has the right power.'};render()}function choose(part){if(s.spell.length>=3)return;s.spell.push(part);s.power+=1;logEl.textContent='You added '+part+'. Meaning is emerging from repetition.';render()}function cast(){const mapping={ka:'move',ru:'open',mi:'light'};const result=s.spell.map(p=>mapping[p]);const ok=s.goal.every(g=>result.includes(g));if(ok){if(s.step===3){logEl.textContent='Your invented language now bends the room itself.';s.goal=['mastered']}else{s.step++;s.power+=2;s.goal=s.step===2?['open','light']:['move','open'];s.spell=[];logEl.textContent='The word worked. The next puzzle needs a richer phrase.'}}else{logEl.textContent='The word failed. The grammar is still incomplete.';s.power=Math.max(0,s.power-1)}render()}function clearSpell(){s.spell=[];logEl.textContent='You cleared the phrase and started a new line of meaning.';render()}function render(){syllables.forEach(function(syl,idx){wordEls[idx].textContent=syl.part+' = '+syl.power});powerEl.textContent=String(s.power);goalEl.textContent=Array.isArray(s.goal)?s.goal.join(' + '):s.goal;stepEl.textContent=String(s.step);spellEl.textContent=s.spell.join('-')||'(empty)'}root.querySelectorAll('[data-pick]').forEach(function(btn){btn.addEventListener('click',function(){choose(btn.getAttribute('data-pick'))})});root.querySelector('[data-cast]').addEventListener('click',cast);root.querySelector('[data-clear]').addEventListener('click',clearSpell);root.querySelector('[data-restart]').addEventListener('click',reset);reset()})});
JS;
if(!function_exists('zo_game_language_builder_render')){function zo_game_language_builder_render($post_id=0,$module=array()){ob_start();?>
<div class="zo-game-root zo-game-root--language-builder">
<h2>Language Builder</h2><p>Invent a language to solve puzzles. Every syllable carries power, and words become tools.</p>
<div class="lb-top"><div class="lb-stat"><strong>Puzzle</strong><span data-step>1</span></div><div class="lb-stat"><strong>Word Power</strong><span data-power>0</span></div><div class="lb-stat"><strong>Need</strong><span data-goal>move</span></div><div class="lb-stat"><strong>Current Spell</strong><span data-spell>(empty)</span></div></div>
<div class="lb-words"><div class="lb-word" data-word></div><div class="lb-word" data-word></div><div class="lb-word" data-word></div></div>
<div class="lb-panel"><div class="lb-btns"><button class="lb-btn" data-pick="ka">Add ka</button><button class="lb-btn" data-pick="ru">Add ru</button><button class="lb-btn" data-pick="mi">Add mi</button><button class="lb-btn" data-cast>Cast Word</button><button class="lb-btn" data-clear>Clear</button><button class="lb-btn" data-restart>Restart</button></div><p data-log></p></div>
</div>
<?php return ob_get_clean();}}
return array('slug'=>'language-builder','name'=>'Language Builder','author'=>'Arslan','description'=>'Invent a language to solve puzzles as words gain power and meaning.','render_callback'=>'zo_game_language_builder_render','inline_style'=>$css,'inline_script'=>$js);
