<?php
if (!defined('ABSPATH')) { exit; }
$css=<<<'CSS'
.zo-game-root--thermal-heist{max-width:860px;margin:0 auto;padding:18px;border-radius:24px;background:linear-gradient(180deg,#0f1622,#232f43);color:#f2f7ff;font-family:"Trebuchet MS","Segoe UI",sans-serif}.zo-game-root--thermal-heist *{box-sizing:border-box}.thh-top{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:14px}.thh-stat,.thh-panel{background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.1);border-radius:16px;padding:12px}.thh-stat strong{display:block;font-size:12px;text-transform:uppercase;color:#c1d0e7}.thh-board{display:grid;grid-template-columns:repeat(8,1fr);gap:6px;background:#09101a;padding:12px;border-radius:18px}.thh-cell{aspect-ratio:1;border-radius:10px;background:#1e2a3d;display:flex;align-items:center;justify-content:center;font-size:20px}.thh-btns{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.thh-btn{border:0;border-radius:12px;padding:10px 14px;background:#ff8c42;color:#182232;font-weight:700;cursor:pointer}
CSS;
$js=<<<'JS'
document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.zo-game-root--thermal-heist').forEach(function(root){const boardEl=root.querySelector('[data-board]'),heatEl=root.querySelector('[data-heat]'),camEl=root.querySelector('[data-camera]'),goalEl=root.querySelector('[data-goal]'),stepEl=root.querySelector('[data-steps]'),logEl=root.querySelector('[data-log]');const coolers=new Set(['2,2','5,5']);const cameras=['7,1','7,3','7,5'];let s;function key(x,y){return x+','+y}function reset(){s={x:0,y:3,heat:8,steps:18,loot:false,log:'You only read heat. Coolers reduce your signature, but movement and touching hot tiles increase it.'};render()}function move(dx,dy){if(s.steps<=0)return;const nx=Math.max(0,Math.min(7,s.x+dx)),ny=Math.max(0,Math.min(7,s.y+dy));s.x=nx;s.y=ny;s.heat=Math.min(10,s.heat+1);if(coolers.has(key(nx,ny))){s.heat=Math.max(0,s.heat-4);s.log='You cooled the surface and blurred your thermal outline.'}if(nx===6&&ny===3&&!s.loot){s.loot=true;s.log='Data core stolen. Now cross the exit without glowing too hot.'}if(cameras.includes(key(7,ny))&&s.heat>=7){s.log='Camera lock. You were too hot to hide.';s.steps=0}else if(nx===7&&ny===3&&s.loot){s.log='Heist complete. You slipped through the scan by managing your heat.';s.steps=0}else{s.log='Thermal scan updates. Keep your signature low near the cameras.'}s.steps--;render()}function render(){boardEl.innerHTML='';for(let y=0;y<8;y++){for(let x=0;x<8;x++){const c=document.createElement('div');c.className='thh-cell';const k=key(x,y);const intensity=Math.max(18,40+s.heat*8-(Math.abs(x-s.x)+Math.abs(y-s.y))*10);c.style.background='rgb('+Math.min(255,intensity+70)+','+Math.max(20,intensity-20)+',30)';if(coolers.has(k))c.textContent='❄';if(k==='6,3'&&!s.loot)c.textContent='◆';if(cameras.includes(k))c.textContent='📷';if(x===7&&y===3)c.textContent='⇢';if(s.x===x&&s.y===y)c.textContent='●';boardEl.appendChild(c)}}heatEl.textContent=String(s.heat);camEl.textContent=s.heat>=7?'Visible':'Blurred';goalEl.textContent=s.loot?'Reach exit':'Steal core';stepEl.textContent=String(s.steps);logEl.textContent=s.log}root.querySelectorAll('[data-move]').forEach(function(btn){btn.addEventListener('click',function(){const m=btn.getAttribute('data-move');if(m==='up')move(0,-1);if(m==='down')move(0,1);if(m==='left')move(-1,0);if(m==='right')move(1,0)})});root.querySelector('[data-restart]').addEventListener('click',reset);reset()})});
JS;
if(!function_exists('zo_game_thermal_heist_render')){function zo_game_thermal_heist_render($post_id=0,$module=array()){ob_start();?>
<div class="zo-game-root zo-game-root--thermal-heist">
<h2>Thermal Heist</h2><p>You see heat, not shapes. Hide by cooling surfaces and keeping your thermal signature low near cameras.</p>
<div class="thh-top"><div class="thh-stat"><strong>Heat</strong><span data-heat>8</span></div><div class="thh-stat"><strong>Camera Read</strong><span data-camera>Visible</span></div><div class="thh-stat"><strong>Goal</strong><span data-goal>Steal core</span></div><div class="thh-stat"><strong>Moves</strong><span data-steps>18</span></div></div>
<div class="thh-board" data-board></div>
<div class="thh-panel"><div class="thh-btns"><button class="thh-btn" data-move="up">Up</button><button class="thh-btn" data-move="left">Left</button><button class="thh-btn" data-move="down">Down</button><button class="thh-btn" data-move="right">Right</button><button class="thh-btn" data-restart>Restart</button></div><p data-log></p></div>
</div>
<?php return ob_get_clean();}}
return array('slug'=>'thermal-heist','name'=>'Thermal Heist','author'=>'Arslan','description'=>'A stealth heist where you read heat instead of shape and hide by cooling surfaces.','render_callback'=>'zo_game_thermal_heist_render','inline_style'=>$css,'inline_script'=>$js);
