<?php
if (!defined('ABSPATH')) { exit; }
$css=<<<'CSS'
.zo-game-root--gravity-swap-rooms{max-width:820px;margin:0 auto;padding:18px;border-radius:24px;background:linear-gradient(180deg,#101726,#1f2e42);color:#f0f6ff;font-family:"Trebuchet MS","Segoe UI",sans-serif}.zo-game-root--gravity-swap-rooms *{box-sizing:border-box}.gsr-top{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:14px}.gsr-stat,.gsr-panel{background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.1);border-radius:16px;padding:12px}.gsr-stat strong{display:block;font-size:12px;text-transform:uppercase;color:#bdd2f5}.gsr-board{display:grid;grid-template-columns:repeat(7,1fr);gap:8px;background:#0d131f;padding:12px;border-radius:20px}.gsr-cell{aspect-ratio:1;border-radius:12px;background:#2a3d57;display:flex;align-items:center;justify-content:center;font-size:26px}.gsr-wall{background:#556980}.gsr-btns{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.gsr-btn{border:0;border-radius:12px;padding:10px 14px;background:#6dc2ff;color:#0f1c2f;font-weight:700;cursor:pointer}
CSS;
$js=<<<'JS'
document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.zo-game-root--gravity-swap-rooms').forEach(function(root){const boardEl=root.querySelector('[data-board]'),roomEl=root.querySelector('[data-room]'),gravEl=root.querySelector('[data-gravity]'),stepEl=root.querySelector('[data-steps]'),logEl=root.querySelector('[data-log]');const rooms=[{walls:['2,0','4,1'],enemy:{x:4,lane:0,dir:-1}},{walls:['1,1','3,0','5,1'],enemy:{x:2,lane:1,dir:1}},{walls:['2,0','2,1','5,0'],enemy:{x:3,lane:0,dir:1}}];let s;function key(x,y){return x+','+y}function reset(){s={room:0,x:0,gravity:1,steps:12,enemy:{x:4,lane:0,dir:-1},log:'Reach the door on the right. Flip gravity to move between floor and ceiling while enemies obey a different lane rule.'};loadRoom();render()}function loadRoom(){const r=rooms[s.room];s.x=0;s.gravity=1;s.enemy={x:r.enemy.x,lane:r.enemy.lane,dir:r.enemy.dir}}function lane(){return s.gravity===1?1:0}function move(dx){if(s.steps<=0)return;const r=rooms[s.room],nx=Math.max(0,Math.min(6,s.x+dx)),ny=lane();if(!r.walls.includes(key(nx,ny)))s.x=nx;enemyStep();s.steps--;check();render()}function flip(){if(s.steps<=0)return;s.gravity*=-1;enemyStep();s.steps--;check();render()}function enemyStep(){const r=rooms[s.room];let nx=s.enemy.x+s.enemy.dir;if(nx<0||nx>6||r.walls.includes(key(nx,s.enemy.lane))){s.enemy.dir*=-1;nx=s.enemy.x+s.enemy.dir}if(nx>=0&&nx<=6&&!r.walls.includes(key(nx,s.enemy.lane)))s.enemy.x=nx;s.enemy.lane=s.gravity===1?0:1}function check(){if(s.enemy.x===s.x&&s.enemy.lane===lane()){s.log='Caught by a ceiling crawler. Restart the room.';s.steps=0;return}if(s.x===6){if(s.room===rooms.length-1){s.log='All rooms cleared. You bent gravity better than the guards could.';s.steps=0}else{s.room++;s.steps=12+s.room*2;s.log='Room cleared. New room, new enemy rule.';loadRoom()}}if(s.steps===0&&s.x!==6&&!(s.room===rooms.length-1&&s.x===6))s.log='Out of moves. Gravity is powerful, but expensive.'}function render(){const r=rooms[s.room];boardEl.innerHTML='';for(let y=0;y<2;y++){for(let x=0;x<7;x++){const d=document.createElement('div');d.className='gsr-cell';if(r.walls.includes(key(x,y))){d.classList.add('gsr-wall');d.textContent='◼'}if(x===6)d.textContent='🚪';if(s.enemy.x===x&&s.enemy.lane===y)d.textContent='👾';if(s.x===x&&lane()===y)d.textContent='🙂';boardEl.appendChild(d)}}roomEl.textContent=String(s.room+1);gravEl.textContent=s.gravity===1?'Down':'Up';stepEl.textContent=String(s.steps);logEl.textContent=s.log}root.querySelector('[data-left]').addEventListener('click',function(){move(-1)});root.querySelector('[data-right]').addEventListener('click',function(){move(1)});root.querySelector('[data-flip]').addEventListener('click',flip);root.querySelector('[data-restart]').addEventListener('click',reset);reset()})});
JS;
if(!function_exists('zo_game_gravity_swap_rooms_render')){function zo_game_gravity_swap_rooms_render($post_id=0,$module=array()){ob_start();?>
<div class="zo-game-root zo-game-root--gravity-swap-rooms">
<h2>Gravity Swap Rooms</h2><p>Flip gravity room by room. You and the enemies follow different lane rules, so every move changes who is safe.</p>
<div class="gsr-top"><div class="gsr-stat"><strong>Room</strong><span data-room>1</span></div><div class="gsr-stat"><strong>Gravity</strong><span data-gravity>Down</span></div><div class="gsr-stat"><strong>Moves</strong><span data-steps>12</span></div><div class="gsr-stat"><strong>Goal</strong><span>Reach each door</span></div></div>
<div class="gsr-board" data-board></div>
<div class="gsr-panel"><div class="gsr-btns"><button class="gsr-btn" data-left>Left</button><button class="gsr-btn" data-right>Right</button><button class="gsr-btn" data-flip>Flip Gravity</button><button class="gsr-btn" data-restart>Restart</button></div><p data-log></p></div>
</div>
<?php return ob_get_clean();}}
return array('slug'=>'gravity-swap-rooms','name'=>'Gravity Swap Rooms','author'=>'Arslan','description'=>'Flip gravity per room while enemies obey different rules than you.','render_callback'=>'zo_game_gravity_swap_rooms_render','inline_style'=>$css,'inline_script'=>$js);
