<?php
if (!defined('ABSPATH')) { exit; }
$css=<<<'CSS'
.zo-game-root--one-button-army{max-width:860px;margin:0 auto;padding:18px;border-radius:24px;background:linear-gradient(180deg,#fbf2da,#e8d4a3);color:#2f2718;font-family:"Trebuchet MS","Segoe UI",sans-serif}.zo-game-root--one-button-army *{box-sizing:border-box}.oba-top{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:14px}.oba-stat,.oba-panel{background:rgba(255,255,255,.55);border:1px solid rgba(47,39,24,.12);border-radius:16px;padding:12px}.oba-stat strong{display:block;font-size:12px;text-transform:uppercase;color:#7a6740}.oba-lanes{display:grid;gap:10px}.oba-lane{display:grid;grid-template-columns:repeat(12,1fr);gap:6px;background:#c8b07a;padding:10px;border-radius:16px}.oba-cell{aspect-ratio:1;border-radius:10px;background:#f8efd7;display:flex;align-items:center;justify-content:center;font-size:20px}.oba-btns{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.oba-btn{border:0;border-radius:12px;padding:10px 14px;background:#7b5c2f;color:#fff;font-weight:700;cursor:pointer}
CSS;
$js=<<<'JS'
document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.zo-game-root--one-button-army').forEach(function(root){const boardEl=root.querySelector('[data-board]'),waveEl=root.querySelector('[data-wave]'),unitsEl=root.querySelector('[data-units]'),goalEl=root.querySelector('[data-goal]'),modeEl=root.querySelector('[data-mode]'),logEl=root.querySelector('[data-log]');let s;function reset(){s={wave:1,index:0,units:[{lane:0,pos:0},{lane:1,pos:0},{lane:2,pos:0}],enemies:[{lane:0,pos:8},{lane:1,pos:10},{lane:2,pos:9}],mode:'march',log:'One button controls every unit. Press Command on the right beat to form a wall or a spear.',done:false};render()}function command(){if(s.done)return;const beat=s.index%4;if(beat===0){s.units.forEach(function(u,i){u.lane=i});s.mode='wall';s.log='Wall formation. Safe, but slow.'}else if(beat===2){s.units.forEach(function(u){u.lane=1});s.mode='spear';s.log='Spear formation. Great for center pushes.'}else{s.units.forEach(function(u,i){u.lane=i===1?2:i});s.mode='chaos';s.log='Bad timing. The army drifts out of shape.'}tick()}function tick(){if(s.done)return;s.index++;s.units.forEach(function(u){u.pos=Math.min(11,u.pos+1)});s.enemies.forEach(function(e){e.pos=Math.max(0,e.pos-1)});resolve();render()}function resolve(){s.enemies=s.enemies.filter(function(e){const hit=s.units.find(function(u){return u.lane===e.lane&&u.pos===e.pos});if(hit){s.log='Formation held. Enemy line broken.';return false}return true});if(s.enemies.some(function(e){return e.pos===0})){s.log='Enemy breakthrough. Restart the drill.';s.done=true;return}if(!s.enemies.length){if(s.wave===3){s.log='Your one-button army mastered timing and cleared all waves.';s.done=true}else{s.wave++;s.index=0;s.units=[{lane:0,pos:0},{lane:1,pos:0},{lane:2,pos:0}];s.enemies=[{lane:0,pos:8+s.wave},{lane:1,pos:10},{lane:2,pos:9+s.wave}];s.log='Wave cleared. New enemy spacing means new timing.'}}}function render(){boardEl.innerHTML='';for(let lane=0;lane<3;lane++){const row=document.createElement('div');row.className='oba-lane';for(let x=0;x<12;x++){const cell=document.createElement('div');cell.className='oba-cell';if(s.enemies.some(e=>e.lane===lane&&e.pos===x))cell.textContent='⚔';if(s.units.some(u=>u.lane===lane&&u.pos===x))cell.textContent='🛡';row.appendChild(cell)}boardEl.appendChild(row)}waveEl.textContent=String(s.wave);unitsEl.textContent='3';goalEl.textContent=s.done?'done':s.enemies.length+' foes';modeEl.textContent=s.mode;logEl.textContent=s.log}root.querySelector('[data-command]').addEventListener('click',command);root.querySelector('[data-tick]').addEventListener('click',tick);root.querySelector('[data-restart]').addEventListener('click',reset);reset()})});
JS;
if(!function_exists('zo_game_one_button_army_render')){function zo_game_one_button_army_render($post_id=0,$module=array()){ob_start();?>
<div class="zo-game-root zo-game-root--one-button-army">
<h2>One Button Army</h2><p>All units share one input. Timing changes the whole formation, so the same button can make a wall, a spear, or a mess.</p>
<div class="oba-top"><div class="oba-stat"><strong>Wave</strong><span data-wave>1</span></div><div class="oba-stat"><strong>Units</strong><span data-units>3</span></div><div class="oba-stat"><strong>Enemies</strong><span data-goal>3 foes</span></div><div class="oba-stat"><strong>Formation</strong><span data-mode>march</span></div></div>
<div class="oba-lanes" data-board></div>
<div class="oba-panel"><div class="oba-btns"><button class="oba-btn" data-command>Command</button><button class="oba-btn" data-tick>Wait Beat</button><button class="oba-btn" data-restart>Restart</button></div><p data-log></p></div>
</div>
<?php return ob_get_clean();}}
return array('slug'=>'one-button-army','name'=>'One Button Army','author'=>'Arslan','description'=>'All units share one input, so timing creates the formation you need.','render_callback'=>'zo_game_one_button_army_render','inline_style'=>$css,'inline_script'=>$js);
