<?php
if (!defined('ABSPATH')) { exit; }
$css=<<<'CSS'
.zo-game-root--loop-factory{max-width:900px;margin:0 auto;padding:18px;border-radius:24px;background:linear-gradient(180deg,#eef5ff,#c8daf5);color:#1d2b41;font-family:"Trebuchet MS","Segoe UI",sans-serif}.zo-game-root--loop-factory *{box-sizing:border-box}.lf-top{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:14px}.lf-stat,.lf-panel{background:rgba(255,255,255,.62);border:1px solid rgba(29,43,65,.12);border-radius:16px;padding:12px}.lf-stat strong{display:block;font-size:12px;text-transform:uppercase;color:#60728a}.lf-line{display:grid;grid-template-columns:repeat(10,1fr);gap:6px;background:#8eabcf;padding:12px;border-radius:18px}.lf-slot{aspect-ratio:1;border-radius:10px;background:#f8fbff;display:flex;align-items:center;justify-content:center;font-size:19px;cursor:pointer}.lf-btns{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.lf-btn{border:0;border-radius:12px;padding:10px 14px;background:#4169a8;color:#fff;font-weight:700;cursor:pointer}
CSS;
$js=<<<'JS'
document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.zo-game-root--loop-factory').forEach(function(root){const lineEl=root.querySelector('[data-line]'),loopEl=root.querySelector('[data-loop]'),outEl=root.querySelector('[data-output]'),effEl=root.querySelector('[data-eff]'),goalEl=root.querySelector('[data-goal]'),cashEl=root.querySelector('[data-cash]'),logEl=root.querySelector('[data-log]');const tools=['·','⛏','⚙','📦'];let s;function reset(){s={line:Array(10).fill('·'),loop:1,output:0,cash:2,log:'Build a 10-second loop. Ore becomes gears, gears become crates, and better placement boosts output.'};render()}function setSlot(i){const current=tools.indexOf(s.line[i]);s.line[i]=tools[(current+1)%tools.length];render()}function runLoop(){let ore=0,gear=0,crate=0;s.line.forEach(function(t){if(t==='⛏')ore++;if(t==='⚙'&&ore>0){ore--;gear++}if(t==='📦'&&gear>0){gear--;crate++}});const bonus=s.line.join('').includes('⛏⚙📦')?1:0;s.output+=crate+bonus;s.cash+=crate;s.loop++;s.log='Loop executed. A clean chain makes more in the same 10 seconds.';render()}function buySlot(){if(s.cash<2)return;s.cash-=2;s.line.push('·');if(s.line.length>12)s.line=s.line.slice(0,12);s.log='You extended the factory line. More loop time, more optimization choices.';render()}function render(){lineEl.innerHTML='';s.line.forEach(function(t,i){const b=document.createElement('button');b.type='button';b.className='lf-slot';b.textContent=t;b.addEventListener('click',function(){setSlot(i)});lineEl.appendChild(b)});loopEl.textContent=String(s.loop);outEl.textContent=String(s.output);effEl.textContent=s.line.join('').includes('⛏⚙📦')?'Linked':'Loose';goalEl.textContent=s.output+'/8';cashEl.textContent=String(s.cash);logEl.textContent=s.output>=8?'Factory optimized. Your loop now prints value every cycle.':s.log}root.querySelector('[data-run]').addEventListener('click',runLoop);root.querySelector('[data-buy]').addEventListener('click',buySlot);root.querySelector('[data-restart]').addEventListener('click',reset);reset()})});
JS;
if(!function_exists('zo_game_loop_factory_render')){function zo_game_loop_factory_render($post_id=0,$module=array()){ob_start();?>
<div class="zo-game-root zo-game-root--loop-factory">
<h2>Loop Factory</h2><p>Build a factory that runs in a 10-second loop. Optimize the order so each cycle creates more value.</p>
<div class="lf-top"><div class="lf-stat"><strong>Loop</strong><span data-loop>1</span></div><div class="lf-stat"><strong>Output</strong><span data-output>0</span></div><div class="lf-stat"><strong>Efficiency</strong><span data-eff>Loose</span></div><div class="lf-stat"><strong>Goal</strong><span data-goal>0/8</span></div><div class="lf-stat"><strong>Cash</strong><span data-cash>2</span></div></div>
<div class="lf-line" data-line></div>
<div class="lf-panel"><p>Click slots to cycle machines: `·` empty, `⛏` ore, `⚙` gear, `📦` pack. A good chain in order boosts output.</p><div class="lf-btns"><button class="lf-btn" data-run>Run Loop</button><button class="lf-btn" data-buy>Buy Slot</button><button class="lf-btn" data-restart>Restart</button></div><p data-log></p></div>
</div>
<?php return ob_get_clean();}}
return array('slug'=>'loop-factory','name'=>'Loop Factory','author'=>'Arslan','description'=>'Build and optimize a factory that repeats on a 10-second loop.','render_callback'=>'zo_game_loop_factory_render','inline_style'=>$css,'inline_script'=>$js);
